### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by will-citi** [zoubin/browserify-postcss#6]
`node build.js` result in error 

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Parsing file c:\apps\projects\learn\browserify-postcss\example\src\entry.css: Unterminated string constant (1:47)
    at Deps.parseDeps (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\index.js:454:28)
    at fromSource (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\index.js:391:44)
    at c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\index.js:385:17
    at ConcatStream.<anonymous> (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:85:20)
    at ConcatStream.emit (events.js:179:7)
    at finishMaybe (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at ConcatStream.Writable.end (c:\apps\projects\learn\browserify-postcss\node_modules\module-deps\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at DuplexWrapper.onend (c:\apps\projects\learn\browserify-postcss\node_modules\readable-stream\lib\_stream_readable.js:504:10)
    at DuplexWrapper.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at DuplexWrapper.emit (events.js:179:7)
    at endReadableNT (c:\apps\projects\learn\browserify-postcss\node_modules\readable-stream\lib\_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zoubin** [comment]
Weird. I don't get this error. Is your clone up to date?

**Comment by ilyhakudrya** [comment]
I'm get this error on Windows, on Mac work fine.

**Comment by zoubin** [comment]
The symlink to `browserify-postcss` in `example/src/node_modules` created on Mac does not work on Windows. I have removed it and made some changes to build.js to make it work on both Mac and Windows.
Thank you for reporting!
